### ISSUE TITLE
Yoda

### ISSUE THREAD

**Issue by loevgaard** [SyliusLabs/CodingStandard#19]
Is there a reason why the yoda style check isn't a part of the Sylius coding standard?

**Comment by pamil** [comment]
No one brave enough to make the decision on it I guess, it's a guaranteed flamewar (even inside Sylius).

**Comment by loevgaard** [comment]
Symfony has it in their code style: https://symfony.com/doc/current/contributing/code/standards.html#structure

I suppose that's a valid argument :)

**Comment by pamil** [comment]
I don't believe the reason behind it is still relevant considering the use of static analysis in every serious project. I always wonder whether anyone made a real mistake and wrote `=` instead of `===` 🎉

**Comment by loevgaard** [comment]
That is a good point
