### ISSUE TITLE
Compatibility with PHP-CS-Fixer v3

### ISSUE THREAD

**Issue by oallain** [SyliusLabs/CodingStandard#37]
Since [PHP-CS-Fixer v3](https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v3.0.0) we got an error :

```
PHP Fatal error:  Uncaught ECSPrefix20210517\Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException: The options "align_double_arrow", "align_equals" do not exist. Defined options are: "default", "operators". in /home/project/vendor/symplify/easy-coding-standard/vendor/symfony/options-resolver/OptionsResolver.php:757
```

Caused by parameters  "align_double_arrow" and "align_equals" that no longer exist.
https://github.com/SyliusLabs/CodingStandard/blob/3cb3800af26912e4dca872526f545b2030111279/ecs.php#L286

Quick fix :

```
composer req --dev friendsofphp/php-cs-fixer:^2.19
```

**Comment by SebLours** [comment]
In the `ecs.php` file after the Sylius configuration import you can also add

```php
$services = $containerConfigurator->services();
$services->set(\PhpCsFixer\Fixer\Operator\BinaryOperatorSpacesFixer::class);
```

**Comment by oallain** [comment]
Thanks @SebLours ,

It's works fine, i thinks i'll make a PR here :)
