### ISSUE TITLE
Stable for a new release?

### ISSUE THREAD

**Issue by Chris53897** [SyliusLabs/CodingStandard#51]
Hi. 
Are these changes ready to be released?
https://github.com/SyliusLabs/CodingStandard/compare/v4.2.1...master
This would help me a bit to solve some dependencies issues.
Update: Of course i am aware of `dev-master`. But this would be a chain reaction in other indirect dependencies. 

But of course i understand that these changes need a proper testing.

**Comment by stefandoorn** [comment]
@Zales0123 Can we release a new version here to allow for the dependency upgrades?

**Comment by Zales0123** [comment]
@Chris53897 @stefandoorn done https://github.com/SyliusLabs/CodingStandard/releases/tag/v4.3.0 :)

**Comment by Chris53897** [comment]
Thanks
